### ISSUE TITLE
Add support for customizing how long the password lives in the clipboard

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#100]
Sometimes with slow networks I feel like I am racing the clock.

**Comment by mbos** [comment]
Will do

**Comment by shaleh** [comment]
On a lark I started working on this. Most of the code is done now. On to testing.....

**Comment by mbos** [comment]
Yeah sorry don't have much time for this hobby at the moment :-)
When you do the push I'll make time to make a release

**Comment by shaleh** [comment]
No worries, we all have lives :-)
