### ISSUE TITLE
Install does not work on Windows 7 x64

### ISSUE THREAD

**Issue by ccryx** [mbos/Pass4Win#102]
Hi,

when I try to install Pass4Win (x64 or x86, 1.2.0.70 or 1.1.9.54), "nothing" happens.
"Nothing" in this case means there are 3 (for the x64 version) or 1 (for the x86 version) unkillable processes that don't display a UI and don't seem to use any CPU.
Additionally, the explorer window the setup is launched from doesn't respond any more.
The only way to kill the processes is to log out or reboot.

If there is anything I can do to help you debug this problem, please let me know.

EDIT:
When I try to extract the setup files for 1.2.0.70 x64 or x86 with 7-zip I get an error saying Pass4Win.exe is corrupted.
I have tried re-downloading the installer but they both have the same MD5 sum.

```
9f9fc32fe8b0e54b55bdf5078a3fd8c5 *Pass4Win-Setup-v1.1.9.54-x64.exe
4d49d96831661451ed8048652595b80e *Pass4Win-Setup-v1.2.0.70-x64.exe
d08f2a0f33a98cb1f4f96e2392ab93a6 *Pass4Win-Setup-v1.2.0.70-x86.exe
```

I get the same error in 7-zip for all the above files and haven't tested any others so far.

**Comment by mbos** [comment]
Extracting doesn't work for me either. It's a standard nsis install that works on my Windows 10 machine the checksums are the same as you posted.
Do you have a virus scanner or something like that which blocks it?
If you want I can give you a zip with the current build in either x64 or x86.

**Comment by ccryx** [comment]
Turns out it was/is my virus scanner (I'm using Avast Free Antivirus).
In order to install and use Pass4Win I need to disable it.
I've added the Pass4Win directory to the scanner's whitelist.
As far as I'm concerned this issue can be closed but you might want to add a note to the readme (or I can open a PR if you want).

**Comment by mbos** [comment]
Ok I'll close the issue and put something in the release notes.
The problem could be circumvented if I would sign the the installer and the executable. Only those certificates cost more money then I'm willing to spend on this hobby :-)
