### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by eworm-de** [mbos/Pass4Win#105]
Testing on Windows 7 32bit I receive unhandled exceptions when adding new items. The generated files are zero size.
![screenshot_2016-09-09_08-39-26](https://cloud.githubusercontent.com/assets/970853/18377840/bdc37e06-7669-11e6-89ed-43e7b3a11392.png)

**Comment by mbos** [comment]
could you please add the logging from typical userdir\Appdata\local\temp\pass4win\pass4win.log. Or you can start pass4win with the -d option to put it in your personal directory.

**Comment by eworm-de** [comment]
I have [git-for-windows](https://git-for-windows.github.io/) installed and decided to try with gpg from that. Obviously git-for-windows comes with gunpg v1.4.20, which does not work with GpgAPI. Probably that is the culprit...

So I caused this myself. The case should be handle by proper error messages, though.

**Comment by mbos** [comment]
Tbh it doesn't look like a GPG error. It looks more like it can't find the git repo. There's a check to see if there are changes:
`RepositoryStatus status = gitRepo.RetrieveStatus();`
`if (status.IsDirty)`

There something goes wrong, what I can imagine is that you have a directory in the root, for example: d:\pass4win. There's a bug in libgit2sharp which ensures an exception. You can then either use an external git program or make it something like d:\blah\pass4win.

**Comment by mbos** [comment]
Due to inactivity
