### ISSUE TITLE
Search not working - always returns "No Value"

### ISSUE THREAD

**Issue by scotte** [mbos/Pass4Win#106]
I'm not sure when or why it stopped working, but the search box is always returning "No Value" for me with 1.2.2. It was working before, on another computer with 1.2.1 (I think). pass4win is otherwise functioning and working just fine.

The log doesn't show anything interesting aside from trying to decrypt a file called "No Value.gpg". I don't know how to debug or provide further details from windows (primary linux user), so let me know any additional details I can provide.

This is on Win 10 pro 64bit.

**Comment by mbos** [comment]
Well that's weird, it just does a regex and when no hits are there it does the No Value thing. Nothing changed in the code between the two versions that would have an impact on search.  Do you have a filename with a regex char in it?
I could make a version with some more output on this if you're willing to test a bit

**Comment by scotte** [comment]
It is weird! All filenames are alpha, numeric, and basic punctuation ("."). I just tried paring down to a minimal pass directory - no .git\* directories, and just a single .gpg entry - I can still reproduce it there. So I don't think it's my repository, maybe something weird on this new computer. I'm more than willing to test with any additional debugging, let me know anything I can do to help track it down. Thanks!!

**Comment by mbos** [comment]
Hey sorry for the late respone, my internet connection was down for a few days. I'll make a special version somewhere next week.

**Comment by scotte** [comment]
Sounds good, thank you!

**Comment by mbos** [comment]
I added some logging to see which file's don't added to the search list. The logging can typically be found in userdir\Appdata\local\temp\pass4win\pass4win.log. Or you can start pass4win with the -d option to put it in your personal directory.
Just replace the exe.

[Pass4Win.zip](https://github.com/mbos/Pass4Win/files/513553/Pass4Win.zip)

**Comment by scotte** [comment]
Thanks! I'll test this out as soon as I can and I'll let you know what I find. Thanks for taking the time to add some debugging!

**Comment by scotte** [comment]
Here's what's in the debug... Every single .gpg file is listed, and looks fine, the paths contain no strange characters, they look like:

```
2016-10-06 20:58:02,750 [1] DEBUG Pass4Win.FileSystemInterface C:\Users\myuser\Somedir\Sync\keys\pass\general\myfile.gpg
```

When I do a search, the following happens:

```
2016-10-06 20:58:03,900 [1] DEBUG Pass4Win.FrmMain Start decryption of: C:\Users\myuser\Somedir\Sync\keys\pass\No Value.gpg
```

Obfuscations are minor but I prefer not to divulge some bits for privacy reasons - just username (a single lowercase word), a directory (which is a single capitalized word) replaced with 'Somedir', and gpg filename, which for all cases I tested here were single word, all lowercase.

So it looks like all the gpg files are properly enumerated, but the regex fails to find a match, the search textbox isn't passing along whatever I type, or who knows what else.

When I reproduced with a simple repo (a single file), the structure was something like D:\tmp\pass\general\myfile.gpg so I don't think my particular directory structure is the cause.

**Comment by mbos** [comment]
Right, thanks for trying, and I understand that you obfuscate a bit :-)
So let's see what's passed along from the textbox. This version has stuff for that :-)
Just to rule out the obvious, what system language / keyboard settings do you have? I do not parse the input to unicode or such.

[Pass4Win.zip](https://github.com/mbos/Pass4Win/files/515464/Pass4Win.zip)

**Comment by scotte** [comment]
Output is exactly the same as before!

```
2016-10-07 19:35:37,077 [1] DEBUG Pass4Win.Program Application started
2016-10-07 19:35:37,114 [1] DEBUG Pass4Win.ConfigHandling Loading config file
2016-10-07 19:35:37,268 [1] DEBUG Pass4Win.Program Checking if not already loaded
2016-10-07 19:35:37,271 [1] DEBUG Pass4Win.Program Load main form
2016-10-07 19:35:37,336 [1] DEBUG Pass4Win.FrmMain Init variables
2016-10-07 19:35:37,397 [1] DEBUG Pass4Win.FrmMain init Bugsnag
2016-10-07 19:35:37,404 [1] DEBUG Pass4Win.FrmMain Getting program version
2016-10-07 19:35:37,407 [1] DEBUG Pass4Win.ConfigHandling Saving config
2016-10-07 19:35:37,446 [1] DEBUG Pass4Win.FrmMain Checking config validity
2016-10-07 19:35:37,454 [1] DEBUG Pass4Win.FrmMain Checking online for latest release
2016-10-07 19:35:37,548 [1] DEBUG Pass4Win.FrmMain Using the internal git executable
2016-10-07 19:35:37,552 [1] DEBUG Pass4Win.GitHandling Init GitHandling
2016-10-07 19:35:44,105 [1] DEBUG Pass4Win.FileSystemInterface C:\Users\...
[...] Lots of files
2016-10-07 19:35:45,041 [1] DEBUG Pass4Win.FileSystemInterface C:\Users\...
2016-10-07 19:35:45,047 [1] DEBUG Pass4Win.FrmMain Start decryption of: C:\Users\...\No Value.gpg
```

That is the entire contents of the log, with only the list of files and paths edited...

System language is US English. Keyboard is default - Nothing unusual as far as I know, it's all whatever the defaults are for USA.

**Comment by mbos** [comment]
OK, I made a mistake, we should see the search results. This weekend is a bit filled :-) will take a good look at the source code with what I know now next week. Thanks so far.

**Comment by mbos** [comment]
Hi,

So it took some while because I needed some time get into the code. Basically the matching regex was bad. It worked before, maybe things got changed or whatever.
I'll release a new version in one or two weeks time.
