### ISSUE TITLE
.exe identified as trojan

### ISSUE THREAD

**Issue by tomolas** [mbos/Pass4Win#109]
My colleague was trying Pass4Win on his windows machine and got a warning from his anti-virus saying: Trojan (HEUR/QVM20.1.0000.Malware.Gen).
Do you know anything more about this?
![screenshot-2016_11_09 14_41](https://cloud.githubusercontent.com/assets/4006600/20140429/5ddb8df6-a68b-11e6-9227-fafac5b85ecb.png)

**Comment by mbos** [comment]
I was a bit curious and downloaded the 64 bit version and put it to through the virustotal scanner. Here's the result:
https://www.virustotal.com/nl/file/8a0c875125875e859b53af9e852f2227461065f2981d0512455ec5937b4da814/analysis/

My own bitdefender and malwarebytes install don't think it's infected.
For what's it worth the builds are automated through appveyor https://ci.appveyor.com/project/mbos/pass4win

**Comment by tomolas** [comment]
Thank you for you answer. I just thought that info could be interesting for you.

**Comment by mbos** [comment]
Yeah I'm interested :-)
Not sure what to do about it though, that 360 doesn't have an online scanner. New version will be out this week though so if your colleague doesn't trust this version he could wait a bit.

**Comment by mbos** [comment]
Just noticed this line:
Qihoo-360       20161103
it passed the online variant of the virusscanner does he have some high heuristics settings?

**Comment by mbos** [comment]
lack of response
