### ISSUE TITLE
Auto update or at least new version detection

### ISSUE THREAD

**Issue by mbos** [mbos/Pass4Win#11]

**Comment by shaleh** [comment]
Git API to the rescue here.

```
REST GET https://api.github.com/repos/mbos/Pass4Win/releases/latest
```

This gives you JSON details about the current release. Save `id` and `tag_name`. Compare them to current somehow. This detail is needed for the About details too so you will have it somewhere.

Is 'latest' newer than installed? If so

```
REST GET https://api.github.com/repos/mbos/Pass4Win/releases/<id>/assets
```

Here you want `browser_download_url` if you want to retrieve it.

None of these calls need to be authenticated just make a HTTP request.

**Comment by mbos** [comment]
Solved with octiikit
