### ISSUE TITLE
Ability to select a leaf folder without selecting a password entry

### ISSUE THREAD

**Issue by kevin8t8** [mbos/Pass4Win#112]
When browsing the folder hierarchy in the left pane, when I select a "bottom level" folder, I get prompted for my passphrase, before I've even had a chance to see the passwords in that folder.  I have to hit Cancel, and then I can choose the actual password entry I am interested in.

It would be nice if I could select the folder and show the list of passwords in it without automatically selecting one of them.

**Comment by mbos** [comment]
You're not caching your passphrase? It's the default on windows to cache it for 2 minutes or so.

**Comment by kevin8t8** [comment]
Yes, I do have passphrase caching enabled.  I mis-phrased it above, I certainly didn't "have" to hit Cancel - I normally could (and should) just enter the passphrase the first time prompted.

In this case, I was browsing the password listings on my wife's laptop to make sure they got synced over, and didn't have her passphrase handy.  So I was repeatedly having to hit Cancel just to browse the hierarchy and see the entries.

I admit this is not the normal situation, so if this is tricky to fix, feel free to close the ticket.  But it did seem odd to be prompted for the passphrase (and I'm guessing the first entry's password copied to the clipboard) before I'd even selected the password I wanted.

**Comment by mbos** [comment]
Ok, I understand your point. The reason the first entry is selected is that it makes no sense to not do that and force you to click twice. I've encountered people who have one entry per directory who would most likely file a bugreport when I change the behaviour :-)

Let's do the following if it's annoying in your normal workflow let me know and I'll implement a switch to choose the behaviour. Untill then I'll close this.
