### ISSUE TITLE
Multiple key : Something went wrong.....

### ISSUE THREAD

**Issue by cedric222** [mbos/Pass4Win#17]
Hi,

I have a pass git with multiple key.
I cannot read password create by others, and the password I create using Pass4win is only readable by me.
(All works correctly using pass in cygwin)
Do you want some debug ?

thanks

cedric

**Comment by mbos** [comment]
Hey sorry for the late reply, strange it uses the same .gpg-id method as pass. If you have additonal info I would be happy to receive it.

**Comment by mbos** [comment]
Not enough info
