### ISSUE TITLE
Installer is in Dutch

### ISSUE THREAD

**Issue by Kwpolska** [mbos/Pass4Win#18]
Even when running on an en_US system.

**Comment by Kwpolska** [comment]
![image](https://cloud.githubusercontent.com/assets/327323/7978972/8214c0da-0a9b-11e5-9039-b744a4720265.png)

**Comment by mbos** [comment]
Ouch, ok I overlooked that :-) will fix it in the next release

**Comment by mbos** [comment]
fixed in release 1.0.1

**Comment by shaleh** [comment]
Again with 1.0.5......

**Comment by mbos** [comment]
Yeah I know. I need to find a way to make a decent install without spending too much learning time. I knew this worked but that it took my system language.....
I'll be trying some easy options and if it all doesn't work out I'll make time to create a NSIS package

**Comment by shaleh** [comment]
No worries. I don't have to read it for a successful install.

https://github.com/activescott/lessmsi looks like a handy tool for examining MSI files.

```
lessmsi l -t Property c:\users\perryse\downloads\pass4win.msi
```

Shows this as part of the output:

```
ARPCOMMENTS,Deze database bevat de logica en de data benodigd om Pass4Win te installeren.
```

So in theory you could implement a release test at some point to validate the file is in the desired language.

**Comment by mbos** [comment]
I made a new setup with NSIS, can you check it for me?
https://s3-eu-west-1.amazonaws.com/pass4win/Pass4Win-Setup.exe

**Comment by shaleh** [comment]
Install is in English. However it fails immediately on first run. I am never asked any config questions.

**Comment by shaleh** [comment]
System.Configuration.ConfigurationErrorsException was unhandled
Message: An unhandled exception of type 'System.Configuration.ConfigurationErrorsException' occurred in System.Configuration.dll
Additional information: Configuration system failed to initialize

**Comment by mbos** [comment]
Made a new installer, this time the git dll's get all included in the same way as in the old installers. Could you try again if this works?
The installer assumes you have .net 4.5 installed (which is default from windows 8 and up)

Same link https://s3-eu-west-1.amazonaws.com/pass4win/Pass4Win-Setup.exe

**Comment by shaleh** [comment]
Successful install. Same failure as above. It did not question me about my configuration and failed almost immediately.
All of the dlls appear to be in place. I have .Net 4.5 and 4.6 installed on Windows 7.

**Comment by mbos** [comment]
Well this is the last thing I can remember. In the original installer the .config was included for some reason. I included that one now also. Could you please try again? It's the same link again:
https://s3-eu-west-1.amazonaws.com/pass4win/Pass4Win-Setup.exe

Thanks for the effort!

**Comment by shaleh** [comment]
Successful install. It is now failing with exception on the unaccessible git repo. Progress? :-)

**Comment by mbos** [comment]
Ugh. Is what we have left the same as issue https://github.com/mbos/Pass4Win/issues/34?

**Comment by shaleh** [comment]
Yes

**Comment by mbos** [comment]
Cool then I will close this one. Thx mate.

**Comment by shaleh** [comment]
One question. How do I test a completely clean install? Where is the config stored so I can remove it?

**Comment by mbos** [comment]
In your user directory:
%UserProfile%\AppData\Local\Pass4Win

**Comment by shaleh** [comment]
Installs fine from clean too. Questions are asked as expected.

**Comment by mbos** [comment]
Finally :-)

2015-09-03 21:19 GMT+02:00 Sean Perry notifications@github.com:

**Comment by shaleh** [comment]
Good job.
