### ISSUE TITLE
Git repository using SSH

### ISSUE THREAD

**Issue by evilstiefel** [mbos/Pass4Win#22]
So I've installed Pass4Win but can't get it to run. When I point it to my existing Git repository for the password store (ssh-based), it crashes after asking for a username and password. When I try to set it up in an empty directory, it requests a git https-style address - is it possible to add support for ssh-based connections?

Regards,
Steffen

**Comment by mbos** [comment]
Hi,
I'm using libgit2sharp for the git implementation. Is has an open pull to implement just this (https://github.com/libgit2/libgit2sharp/pull/1072). When and if this get's to the main branch I'll add it as a choice. I'll look into the crash, that obviously shouldn't happen.

Thanks for the feedback,
Mike

**Comment by mbos** [comment]
090e274f4e4e425a9339a77fa9abc9522d76887e

**Comment by mbos** [comment]
https://github.com/mbos/Pass4Win/releases/tag/version-1.1.8
