### ISSUE TITLE
Command line program?

### ISSUE THREAD

**Issue by Ciantic** [mbos/Pass4Win#24]
Original pass program is a shell script. I wonder if all this knowledge could be used to implement pass program in C#, and have it working on multiple platforms.

I could not get the UI to work, it throws some random errors. Got three different things already.

**Comment by mbos** [comment]
Well yes a command line version would be easy to make.

What errors did you get in the UI, knowing the specifics I could fix it.

**Comment by mbos** [comment]
Not enough info
