### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by Rrego6** [mbos/Pass4Win#27]
Would be useful for debugging program if these were made clear.

**Comment by mbos** [comment]
I'm using Visual Studio 2013 community edition. It's build with that, no special parameters, you can use the solution file to load it and it should load correctly and build correctly.

**Comment by Rrego6** [comment]
I downloaded Visual Studio 2013 (since I was having errors in 2015) and am having issues building the program. I'm unable to import the vdprodj  for the install file since I don't think they are supported anymore. I also have a certificate error and can't seem to find anything about certs in the csproj file. Program is also unable to find schema, is that setup in the install?

**Comment by mbos** [comment]
Weird, the program and the setup is in the same solution file. Maybe opening the project. It depends on two other projects GpgAPI  and LibGit2Sharp. Both I got with nuget, maybe those are missing?

**Comment by Rrego6** [comment]
Eh. Wasn't able to do it. I believe nuget is included in all recent visual studios. I'm also sure both of those projects were retrieved when importing. Still not sure about the schema errors though. Perhaps your system in configured in such a way when you import.

**Comment by mbos** [comment]
Sorry for the late reply was on vacation. Anyway, I'll upgrade to 2015 and let's try again then. May take a while though, but on the latest next month

**Comment by Rrego6** [comment]
Thanks. Looking forward to it.

**Comment by mbos** [comment]
Migrated it to 2015. Removed the certificate thing (was a cllckonce) and removed the installer, it wasn't compatible.
Should work now. I'll keep the installer seperate.
