### ISSUE TITLE
Stuck without ability to set repo

### ISSUE THREAD

**Issue by DeastinY** [mbos/Pass4Win#28]
Did something, stuff crashed now it skips the dialogue to set the remote repo - instantly goes to username / password then closes without any word ^^
Am on Windows 10 btw.

**Comment by mbos** [comment]
You could delete the %UserProfile%\AppData\Local\Pass4Win folder. It removes the saved settings for password directory, repo, user and pass.

If you find what you did I would be intrested :-)

**Comment by DeastinY** [comment]
Worked :)
Thanks a bunch !
