### ISSUE TITLE
Nothing happens when I provide a blank remote

### ISSUE THREAD

**Issue by mkaito** [mbos/Pass4Win#29]
According to the window title, I should leave the remote field blank to not use a remote. So I do, and then nothing happens. The program just closes.

Background: I want to access my passwords. My password store was created on a Linux installation, and I want to use Windows for gaming purposes, and store my game passwords in the same password store. I'm keeping things synchronized using rsync, so there's no direct need for a git remote on Windows.

**Comment by mbos** [comment]
Hey, was this with 1.0.3? I thought I fixed that bug

**Comment by mkaito** [comment]
Yep, it's 1.0.3

**Comment by mbos** [comment]
Should be fixed now: 193ecf597ab72c24414fc4c2b5a6d1864fa6bc59

**Comment by mkaito** [comment]
I'll have to wait for a new release to test.

**Comment by mbos** [comment]
https://s3-eu-west-1.amazonaws.com/pass4win/Pass4Win-Setup.exe
Is the current source compiled

**Comment by mkaito** [comment]
It appears to work.

One question I have, though. When I open the application, it immediately asks for my gpg password and copies the first password in the list to the clipboard. It seems like clicking on another element in the list copies it. However, when searching for something, and only one result is shown, this result is already selected, and not copied. Clicking on it doesn't seem to do anything. Is this a bug, or am I doing something wrong?

**Comment by mbos** [comment]
The timer works here, in the code it's whenever the selection is changed. I added a copy option to the right click menu in 7642b642c95a209a1fd44b2da350b21576a70f19

Oh and before I forget :-)
Thanks for the feedback!

**Comment by mkaito** [comment]
Could you post a compiled version of HEAD, with the right click to copy feature?

**Comment by mbos** [comment]
It's in the 1.06 release (https://github.com/mbos/Pass4Win/releases/tag/version-1.0.6)
Op 6 sep. 2015 14:31 schreef "Chris Hoppner" notifications@github.com:
