### ISSUE TITLE
git:// is supported but the UI says "https"

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#30]
It was WAY easier to run git in hub mode on my Linux box long enough to sync than to install and set up a web server, fast cgi, et al just to have a http(s) accessible git repo.

Please update the documentation and the UI.

Thanks for the app.

**Comment by mbos** [comment]
Did you try it? The GUI has the text, but no checks.

**Comment by shaleh** [comment]
Yes git:// works. But I spent time trying to get https working first because of the text and lack of documentation.

**Comment by shaleh** [comment]
```
[alias]
serve = !git daemon --base-path=. --export-all --reuseaddr --informative-errors --verbose
hub = !git daemon --base-path=. --export-all --enable=receive-pack --reuseaddr --informative-errors --verbose
```

Now I can 'git hub' long enough to sync and then kill it. Quite handy and super easy.

**Comment by mbos** [comment]
I'll change the text of the ui, sorry for the oversight (816541f3bf1f563f33dad36b2aed2b9c80c8bde8)

**Comment by shaleh** [comment]
No worries. Thanks for the app.
