### ISSUE TITLE
Don't show my passwords please

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#31]
My passwords are stored in multiline files that look like:

```
password
Username: some_user
URL: https://example.com
```

The UI shows all of my passwords all of the time.

**Comment by mbos** [comment]
So basically now it's unlock once (or till timeout gpg_agent) and when you select an entry it shows all the info. Do you want it locked again or simply not automatically visible? And if not visible do you want it copied to the clipboard automatically or not?

Thanks for the feedback.

**Comment by shaleh** [comment]
I never want it to show a clear text password without me directly choosing "show me the password". I often have coworkers sitting with me while we debug and hack. There are too many passwords that change every so many days so I use an app like this to keep them straight. But I also have other passwords that do live longer that I don't want them to see.

My expectation is unlocking the app and then somehow choosing an entry to cut&paste. I never need to see the password unless I am typing it on another system.

**Comment by mbos** [comment]
Sounds reasonable, I'll think it over on how too implement that and include it in the next release.

**Comment by mbos** [comment]
Solved 64d8bb631090611249e5fe22480b6466b306aa28

Made a button you need to press to make it visible.
Selection changed or timer from copy/paste make it invisible again

Good enough?

**Comment by shaleh** [comment]
As soon as I have a working VS2015 install I will let you know :-)

**Comment by mbos** [comment]
Just grab the new release :-)

**Comment by shaleh** [comment]
Uncertain. I ran setup.exe to install the new version. It once again asked me where to store things, where is gpg2, remote user/password. Now the app dies whenever I start it.

More details once VS2015 finishes installing.

**Comment by shaleh** [comment]
The Repository.IsValid(Properties.Settings.Default.PassDirectory) check is blowing up with an exception.TypeInitializationException it says.

Learning how to build the libgit2sharp depends now.

**Comment by mbos** [comment]
Use nuget https://www.nuget.org/packages/LibGit2Sharp

**Comment by shaleh** [comment]
It is failing inside the libgit2sharp lib that is why I was trying to build it. Just not had time to hack on it yet.

**Comment by mbos** [comment]
It may be that it's missing a dll. I still need to find a way to reliable
pack the git dll (
https://github.com/mbos/Pass4Win/blob/master/Pass4Win/git2-e0902fb.dll)
into the oneclick setup. I'll look further into that this week. You can
check into the install directory if the dll exists there

2015-08-31 6:33 GMT+02:00 Sean Perry notifications@github.com:

**Comment by shaleh** [comment]
Looks better. Thanks,
