### ISSUE TITLE
Please implement a tray icon

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#32]
I often have quite a few apps running. Finding the open Pass4Win window is a bit annoying.

Have you used something like pwsafe? It implements a really handy tray icon. You click it and the main window appears after you have unlocked it. Closing that window does not exit the app.

It would be nice to have similar functionality here. I am a Unix coder or this would be a pull request instead of an issue. Maybe someone else will jump on it before I get to it :-)

**Comment by mbos** [comment]
Good suggestion!
476f45b56685e6b44693bcea6c0e378614953eaf
And done

**Comment by shaleh** [comment]
The hint is "trayicon1".

**Comment by mbos** [comment]
Oops. Fixed
