### ISSUE TITLE
Don't show password during install time questions

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#36]
The remote password field is clear text and should not be. It would be ok if it had a checkbox for "show password" or the like but it should not show by default.

**Comment by mbos** [comment]
Fixed: 193ecf597ab72c24414fc4c2b5a6d1864fa6bc59

**Comment by shaleh** [comment]
New release soon?

**Comment by mbos** [comment]
Yeah 1.0.6 is downloadable
