### ISSUE TITLE
App fails with exception when build from source

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#37]
```
An unhandled exception of type 'System.TypeInitializationException' occurred in LibGit2Sharp.dll
Additional information: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
```

This happens at the call to Repository.IsValid. Version mismatch perhaps? Might be related to my issue #35.

**Comment by mbos** [comment]
I'm using version 0.21.0.176 through nuget. I know that the new version has some new calls. I updated it for a beta, but not sure for the latest build

**Comment by shaleh** [comment]
Sorry for my flailing around. I can drift around mountains on Unix but on Windows I still drive like a teen learning a manual transmission.

**Comment by mbos** [comment]
No worries, I love it that you get feedback!

**Comment by shaleh** [comment]
Ok, I tried to build from the 1.0.5 source zip. The build retrieves bits via nuget and the app does indeed run. I updated my other issue with more details on the Exception.

Side bar, I like the MSI. Could you name it "pass4win.msi" so when I go looking in my Downloads folder I can find it :-)

**Comment by mbos** [comment]
Yeah :-)

**Comment by shaleh** [comment]
Works with current master.
