### ISSUE TITLE
needs better support for inaccessible remote repos

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#43]
If you choose to have a remote the installer requires the remote to be online even when there is already a populated password store.

The UI for later use requires going into the Config and clicking "use remote git repo" again. Ideally there would simply be a "sync now" button/menu/something. Or a "go online".

**Comment by shaleh** [comment]
Would you prefer I break this into two issue?

**Comment by mbos** [comment]
No it's ok like this.

**Comment by mbos** [comment]
Instead of a button (sync or whatever) would a check every x minutes work too?

**Comment by shaleh** [comment]
Problem is I routinely run without connectivity to my workstation. It may be a day or a few days between sync ups.  I do not add or modify my passwords daily. More like weekly or even biweekly. I suspect many are in a similar position. The command line version requires you to run 'pass git push' or the like.

In terms of battery, network, etc. any kind of "is git alive" check would just be wasteful for a common use case. From a programming perspective, a simple way to toggle "online" or not is the baseline required functionality. Connecting that to a timer or a button afterwards is pretty straightforward.

**Comment by mbos** [comment]
I'm looking at the source but it seems that when you first config it and set the remote checkbox it checks if the remote is online and if not sets it to offline with an error message.
Is that wrong or did it work different for you?

**Comment by shaleh** [comment]
I think the code itself is working as you intended. I am arguing that the UX is not up to par.

On first config I know I do have a remote so I click the box. I enter the info. However, I am at home, not work. So the git repo is not available. I cannot proceed without disabling the "use remote" check box. I should be able to configure it and have the application detect I am "offline" and allow me to continue. Potentially with an incorrect config if there is a typo. later when I know I can go online the application can let me know if something breaks.

**Comment by mbos** [comment]
Ah ok, I always want to check all input and when not possible input it later. Tbh I can see advantages and disadvantages to both approaches.
Thinking about it this is what I'll do for both initial config and normal operation:
1. check if stuff is semantically correct
2. check if alive
3. if !alive fail silently and put the offline txt. Do not change config info (checkbox)
4. if someone presses the sync button and something fails tell them what.

Ok? Any ammends?

**Comment by shaleh** [comment]
Sounds right.

**Comment by mbos** [comment]
fixed in ebe8cd70

**Comment by mbos** [comment]
Released, let me know if it works :-)

**Comment by shaleh** [comment]
Looks good.
