### ISSUE TITLE
Add version number to released setup program

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#44]
This makes it easier to test upgrades, etc.

**Comment by mbos** [comment]
Will do.  As it will be a silent install only in the setup name.

**Comment by shaleh** [comment]
To be clear I am asking for Pass4Win-setup-1.0.6.exe. Or similar.

**Comment by mbos** [comment]
fixed in a1c5b9ae.
Name will be generated from the version info ie Pass4Win-Setup-v1.0.7

**Comment by shaleh** [comment]
Thank you.
