### ISSUE TITLE
Crash on creating/editing password

### ISSUE THREAD

**Issue by cmol** [mbos/Pass4Win#47]
Hi

I have an existing pass repository that I cannot add passwords to. Using the 1.0.7 installer I can point to the newly cloned repo, and read all the passwords as I am supposed to.

When adding a password the program crashes with:

```
************** Exception Text **************
LibGit2Sharp.EmptyCommitException: No changes; nothing to commit.
   at LibGit2Sharp.Repository.Commit(String message, Signature author, Signature committer, CommitOptions options)
   at Pass4Win.frmMain.Encrypt_Callback(GpgInterfaceResult result, String tmpFile, String tmpFile2, String path)
   at Pass4Win.frmMain.txtPassDetail_Leave(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnLeave(EventArgs e)
   at System.Windows.Forms.Control.NotifyLeave()
   at System.Windows.Forms.ContainerControl.UpdateFocusedControl()
```

Any ideas?

**Comment by mbos** [comment]
I can see how nothing to commit could throw an exception (I'm not testing for an exception). I'm just not sure how that could happen and can't reproduce it.
From what I'm aware of there are two situations this can happen:
1. There is .gitignore file that excludes the files
2. the .git directory path is screwed (a reinit may work)

Could you try a console commit to check if a changed file is commited or "No changes; nothing to commit" comes back? That's basically tells us if this is a git issue or a pass4win issue. If it's commited I really need more information could you describe the things you do to crash it?

Thanks!

**Comment by cmol** [comment]
Ok, so via git bash I echoed something into a file in the repo, ran git add [path/to/file], git commit -m "commit", and everything worked fine.

My steps to reproduce the error are:
- git clone repo with passwords (that is used on linux and osx)
- Open pass4win (latest version)
- Click "Add" to add a new password and enter a name for it. "test.com/claus1" in this case
- Click edit on the password I just named
- Enter credentials in box to the right
- Either click another password or click add again to "save" the data
- Error occurs

Only when I press a password that is encrypted on Linux or OSX the gpg-agent pops up and asks for a passphrase, so not when I'm creating the password.

The files them self are created (test.com/claus1.gpg is actually there), but are empty files.

There is no .gitignore file.

.gitattributes has:

```
*.gpg diff=gpg
```

.git/config has:

```
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
        hideDotFiles = dotGitOnly
```

, along with remotes and such.

I have also with earlier versions of pass4win added passwords that turned out to be empty files, that somehow got committed into the repo.

Thank you and let me know if you need anything else from me :)

**Comment by mbos** [comment]
Thanks for the quick reply!

I tried to reproduce it and no dice. I can edit and stuff goes how it should be. Obviously the add process should be smoother ( #48).

The weird thing is that the keymanager dialog popups after selecting something. It should pop up at startup as the first entry should be decrypted as it's automatically selected.
Is your first .gpg entry a valid gpg encrypted file? 

Looking at the code I still can't explain this. It might be something with keys present in the .gpg-id and not in the as a secret key in the keystore of gnupg. It may be that there is a write error that GPGApi doesn't catch (I test on succes so a bit doubtful that one).

Could you check the .gpg-id listed keys against your keystore and what's up with your first show entry?

Thanks.

**Comment by cmol** [comment]
Ok, so the first entry was one of my dead test entries, so I deleted it and now the agent pops up on startup, but the created passwords are still bad.

I checked the `.gpg-id`-file and three names of keys that I expected there was there as they should. When I looked with `gpg2.exe --list-keys`, all the keys was there as they should, but using Kleopatra, only my own key and a key from keybase was there, not the two other pubkeys that should be there.

So I updated the keys with keybase and now I can create new passwords and push them, but with no content (empty files). 

I could still not see my keys with Kleopatra so I started searching. It turns out that Kleopatra uses somewhere down in AppData for the user to store keys, and gpg2.exe looks inside $HOME/.gnupg, so I imported the keys in kleopatra, but I still get empty passwords. I am getting the feeling that this is a issue with how I've installed gpg in this test setup.

Can you tell me how my files should be placed on windows?

Thank you, and sorry if this is a trivial thing I haven't understood. I'm trying to get pass4win working for the windows people in my department, and is a bit out of my normal environment :)

**Comment by mbos** [comment]
Ok so we have at least explained the agent popup :-)

I just installed the http://www.gpg4win.org/ full version but looking at my own setup my keys are in C:\Users\mikeb\AppData\Roaming\gnupg. Both Kleopatra and gpg2.exe get the keys from there.
I have a default install, The documentation from gpg4win states that %APPDATA%\gnupg is the directory it should look.
I'm not sure what the fix is :-) as it's windows a reinstall may be better then fiddling with the settings.

I opened  #49 to address the issue in the code. I'm glad we may found the cause. Let me know how it works out and if I can help let me know. Very interested how this pans out :-)

**Comment by cmol** [comment]
I will try reinstalling gpg and keybase then. It sounds like the right thing to do.

It might be a week or so before I get back to you, my weekend is pretty booked :)

**Comment by mbos** [comment]
Have a nice weekend, and just googled keybase, didn't know it. Will try it out.

**Comment by mbos** [comment]
Oh invitation only, oh well requested access to the beta

**Comment by cmol** [comment]
Hand me you email, I have a few invites left :)

**Comment by mbos** [comment]
Nice thanks. 

Mikebos at mik3 dot com

**Comment by cmol** [comment]
Ok, so I tried removing all GPG, keybase (with node) and all. Removing files from down in AppData and everything. (why isn't this done by the uninstaller......)

When reinstalling everything I found that I needed to track people again with keybase before getting their pubkeys, I'll make a ticket with them, but after tracking the 2 other people I'm testing with, I can now see all the keys as I should in kleopatra. There is no .gnupg folder in my "home" folder, rather things are located down under `AppData/Roaming/gnupg` as it should be.

When running `gpg2.exe --list-keys` (in powershell) I can see the pubkeys I have in my .gpg-id. When running the command from a git-bash shell it nags about .gnupg being absent in my home dir, which is should be.

However, I still get the same error when adding passwords as I did originally. Is it possible to run pass4win with command line args that makes it verbose about the communication with gpg and what gpg sends back?

**Comment by mbos** [comment]
No there are no command line options for the verbose thing. But I finally
get what's wrong. Pass4Win needs the secret key to be present. I'm not able
to check now, but I suspect I only list the secret keys.
I'll correct this in the next version.

Thanks for looking into it.

Mike

2015-09-23 11:24 GMT+02:00 Claus Lensbøl notifications@github.com:

**Comment by cmol** [comment]
Sounds like it could be the problem. Just tell me when you have an update and I'll test it for you :)

**Comment by mbos** [comment]
Sent you a build through the email (keybase.io)

**Comment by mbos** [comment]
Was an issue with matching keys. Solved in the main
