### ISSUE TITLE
New installer is too silent

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#51]
Install 1.1.0 on top of an existing install and the setup simply starts and exits. No indication it ran, nothing. It is only by starting the app that I can tell anything happened.

**Comment by mbos** [comment]
I suppose the decent thing to do would be to start the app up after install and including a command line switch to keep it silent. I'll look into it.

**Comment by mbos** [comment]
0375ba0293b44060f06bb7385ea89575f4cc055a

It now observers the /S flag and otherwise it behaves as a normal install
