### ISSUE TITLE
App exits when the window is closed

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#53]
The whole idea of having the tray icon is that it is the real app. The window is just a temporary view.

**Comment by mbos** [comment]
That's not what you originally requested, or at least how I understood it :-)
I have no idea what the impact is, but I guess it's a bit of a rewrite for the whole GUI. I'll do this if there are enough issues to warrant the rewrite.

**Comment by shaleh** [comment]
No benefit to the tray icon if there is also a window open :-) Well, I take that back it makes it easier to find it kinda. I can look in the tray instead of in the list of open programs on the bar.

It should be not be that bad. Just catch the exit when the user clicks X and close the window instead of application quit. Clicking the tray icon just spawns a new window.

**Comment by mbos** [comment]
Hmm you're right not a very difficult change
