### ISSUE TITLE
Not syncing with git

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#54]
If i inspect the local git repo on my WIndows box it says it is 3 commits ahead of my upstream repo. I do not see the offline message at the moment and my git server is currently visible. I tried clicking the Config button to jog it but that is not helping. Watching my server I see Pass4Win ping the server but no commits are made.

**Comment by mbos** [comment]
Ouch never realized, pushes only happen when something has changed. I never check if a push is needed on startup or offline to online switch.

**Comment by shaleh** [comment]
That is one of the reasons I originally requested a "sync" button/choice. So I knew it happened :-)

**Comment by mbos** [comment]
Right made the check which runs when the state is changed (toolbar click), the config is changed or the program is started
