### ISSUE TITLE
Make app portable

### ISSUE THREAD

**Issue by mbos** [mbos/Pass4Win#56]

**Comment by Anachron** [comment]
Hey there, what is the state here?

**Comment by mbos** [comment]
No real progress. I fooled around a bit, the main problem is that I would need to implement an openpgp variant into the project. Even with a ready lib that's a lot of work, frankly more then I want to do at this point in time.

**Comment by Anachron** [comment]
What's wrong with https://www.gpg4win.org/ ? It seems to work with your tool.
I extracted the contents of Pass4Win-Setup-v1.2.1.9-x64.exe, made the portable gpg4win version and now I only get some issues with my .NET-Version. But it starts and let me even choose the GPG key I was generating with gpg4win!

**Comment by mbos** [comment]
Huh never knew that was possible :-)
I'll look into it.

**Comment by mbos** [comment]
I included all the needed .net binaries and added the instructions to make a gpg4win portable in the wiki

**Comment by Anachron** [comment]
Great, thanks!
