### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by mkaito** [mbos/Pass4Win#74]
The filter function seems to run immediately when the text in the input field changes. On every single key press. And then it will try to decode the first match and start the timer. It usually takes upwards of 10 seconds to get to where I want, and by the time the interface updates, the timer is almost done. Perhaps implement a delay?

On that note, the clipboard timer is _way_ too short. The original pass defaults to 45 seconds, while the android app goes for 120s to compensate for the slower interface. I think 45-60 seconds is perfectly fine.

**Comment by mbos** [comment]
Thanks for the feedback!

The filter function runs on a 0,5 seconds delay, the number was chosen by the same process as how I choose the 30 seconds. It worked for me :-)

I'll make both timers configuration options and set the default for the clipboard to 45 sec.
The filter function is completly rewritten in the next release so that should help with the delay.

Cheers,

Mike

**Comment by mkaito** [comment]
Thanks!

**Comment by mkaito** [comment]
Wait, the clipboard timer is meant to be 30 seconds? It's more like 5 seconds for me. I have to literally hold the mouse cursor over wherever I want to paste the password so I can immediately click and paste.

**Comment by mbos** [comment]
Just checked the code on my mobile, it looks like it is 1 sec now. No idea
how that happened.
Op 21 okt. 2015 5:14 PM schreef "Chris Hoppner" notifications@github.com:

**Comment by mbos** [comment]
So this is why I should no check on mobile. Currently it's set for 45 seconds. I made the thread somewhat safer, it lacked a check if it needed to be fired on a different thread or could be fired in the main thread.
For the rest it's a standard timer and given the interval it shouldn't give any problems. I can't find anything on google about a timer going to fast....

Did you look into your errorlog?

Cheers,

Mike

**Comment by mkaito** [comment]
I'm not even sure how to check an errorlog on windows. Sorry, but I'm a Linux guy :stuck_out_tongue:

**Comment by mbos** [comment]
Okay on windows 10 type log in your search box, the application should be called something like logbook or whatever the translation in your locale is.
In the tree select windows log -> applications. There's a shitload there and it being windows you can't grep easy through it, so just start the application wait for the timer and look if something happens in the log.
Any other windows version: Almost the same :-)

**Comment by mkaito** [comment]
Alright, I'll check when I reboot. Thanks :smile:

**Comment by mkaito** [comment]
No, there does not seem to be anything in the error log... unless I'm looking in the wrong place.

Windows 7, search for "log", View Event Logs, Windows Logs, Application. Huge list of things, can't even see pass4win mentioned anywhere.

The way it looks to me, the filter runs on every key press regardless of internal timer.

**Comment by mbos** [comment]
Okay weird. You could try out the new release, although nothing specific happened to address this issue some things may have had some impact on this (dll inclusion and more null checking).

I'll look into this and make for the next release the times configurable.

**Comment by mbos** [comment]
Inactive
