### ISSUE TITLE
HiDPI awareness (blurry fonts on HiDPI displays)

### ISSUE THREAD

**Issue by drdaeman** [mbos/Pass4Win#81]
I'd suggest to add basic awareness to the app, as it'd otherwise look awfully blurry on high-PPI displays. An imperfect but simplest way to do so is to just call [`SetProcessDPIAware`](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms633543%28v=vs.85%29.aspx) at the startup.

```
[System.Runtime.InteropServices.DllImport("user32.dll")]
private static extern bool SetProcessDPIAware();

[STAThread]
static void Main()
{
    if (Environment.OSVersion.Version.Major >= 6) { SetProcessDPIAware(); }
    Application.EnableVisualStyles();
    Application.SetCompatibleTextRenderingDefault(false);
    ...
```

This doesn't support per-monitor DPI settings, which require monitoring which monitor windows are on and adjusting things, but application would look way better on single-monitor HiDPI systems (e.g. laptops) and won't look too bad on multi-monitor ones, as bitmap downscaling is generally better than upscaling.

**Comment by mbos** [comment]
Added and thanks for your suggestion
