### ISSUE TITLE
Does not start (Windows 10)

### ISSUE THREAD

**Issue by Cardridge** [mbos/Pass4Win#82]
No error / debug message, nothing. Not sure what to do.

gpg and git are installed.

**Comment by mbos** [comment]
Hiya,

You could look into the application error log. In your searchbar type log and the logbooks shortcut should come up.
For what it's worth, I'm running windows 10, so that isn't the issue.

Cheers.

Mike

**Comment by Cardridge** [comment]
This seems relevant:

```
Faulting application name: Pass4Win.exe, version: 1.1.4.0, time stamp: 0x56328bab
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f3b2a
Exception code: 0xe0434352
Fault offset: 0x000b3e28
Faulting process ID: 0xfcc
Faulting application start time: 0x01d118cdd52bfb10
Faulting application path: C:\Program Files (x86)\Pass4Win\Pass4Win.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report ID: a08d3dcd-4ccb-40af-8815-acca2d660c6a
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by mbos** [comment]
The error code means there is an unhandled exception in the Pass4Win application. Not really helpfull :-)
The next release will have a lot more exception handling, so maybe wait that one out.

**Comment by Cardridge** [comment]
Thanks for the reply and will do.
