### ISSUE TITLE
1.16 believes it is 1.1.6

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#85]
This means it always believes there is a newer version.

**Comment by mbos** [comment]
Typo in the release title on GitHub. I added the missing punctuation so it should clear up in a while.

**Comment by mbos** [comment]
Well.... 

```
var newversion = releases[0].TagName.Remove(0, 8);
```

And the tag is version-1.1.6-final... Go figure.

**Comment by mbos** [comment]
```
var newversion = releases[0].TagName.Remove(0, 8);
newversion = newversion.Remove(5);
```

**Comment by mbos** [comment]
I will release a new version end of the week, as popups are annoying
