### ISSUE TITLE
Says I have 6 safes but I cannot access them

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#86]
The UI is just missing.
![no-passwords](https://cloud.githubusercontent.com/assets/1377996/11404835/f8a0c064-9358-11e5-9a28-43cf4257a905.png)

**Comment by shaleh** [comment]
Ignore the notification please. It is not relevant.

This shows the incorrect version I reported in #85

**Comment by mbos** [comment]
Did you try to reset the config?
If so could you please pass a name listing of the 6 entries?

**Comment by shaleh** [comment]
Deleting the config and re-configuring did resolve the problem.

BTW, documenting the config file name and location would be helpful.

**Comment by mbos** [comment]
True that. Made a FAQ https://github.com/mbos/Pass4Win/wiki/FAQ
