### ISSUE TITLE
Allow SSH keys

### ISSUE THREAD

**Issue by PerlStalker** [mbos/Pass4Win#88]
I have my password database in a repo host on a private gitlab server. To use SSH, gitlab requires the use of keys. I don't see a way to specify a private SSH key in the pass4win configuration.

A related issue is that the config interface wouldn't let me specify a git URL in the format git@hostname:user/password-store.git. It gives an error about an invalid format.

**Comment by mbos** [comment]
Hey mate,

Thanks for the feedback.
So in issue #22 it states Pass4Win doesn't support SSH. It even says it in the config dialog: **Git or HTTPS**
So you need to select the https link to your repo, so far as I know gitlab supports or supported that.

Cheers,

Mike
