### ISSUE TITLE
Add support for an external git installation

### ISSUE THREAD

**Issue by mbos** [mbos/Pass4Win#89]

**Comment by mbos** [comment]
090e274f4e4e425a9339a77fa9abc9522d76887e

**Comment by toXel** [comment]
Wow that was fast :D as soon as I'm home again I will test it out :)

**Comment by mbos** [comment]
Don't hurry to much, it's only backend code as of yet. Still need to change 
the GUI ☺

Cheers,
Mike

Op 1 januari 2016 4:27:32 PM schreef Timo notifications@github.com:

**Comment by craftyguy** [comment]
Does this also include support for connecting to SSH via a socks proxy? Unfortunately my only Windows system is behind a proxy :(

**Comment by mbos** [comment]
not sure, it uses the git installation that you installed yourself. So if you have set up a global proxy option ie git config --global https.proxy 'socks5://127.0.0.1:7070' I see no reason why it shouldn't work.

**Comment by craftyguy** [comment]
ah, yea seems like it would work then.. didn't realize the library you're using uses my local git install. Do you have any plans to support push/pull so that users can easily keep their repos up to date with Pass4Win?

**Comment by mbos** [comment]
The next version there will be two choices in regard to git:
- Use the internal git lib
- Use the local installation

Push/pull is already implemented. Changes and additions are pushed 
(added) and with fetch remote changes are synced. This works for the 
current version.

**Comment by craftyguy** [comment]
Thanks for the clarification.. can't wait to try this out, since this functionality is the main thing keeping me from migrating fully to using pass on all of my systems :)

**Comment by mbos** [comment]
[BETA-release.zip](https://github.com/mbos/Pass4Win/files/81103/BETA-release.zip)

I tried a couple of scenario's and it seems like it works :-) everyone who want to try it out, here is the beta. Give some feedback and I'll improve or if it works fine the first time....... I'll release.

**Comment by toXel** [comment]
As far as I can see it works! Thank you so much :)
Tomorrow I will do more testing behind a proxy server.

**Comment by mbos** [comment]
Nice to get the feedback! Thanks.

**Comment by toXel** [comment]
Git sync behind a proxy works flawless for me with the externel git installation. Thank you!

**Comment by mbos** [comment]
Okay great, I'll make a request for translation and release it asap

**Comment by toXel** [comment]
I've just added the German translations. Maybe someone could approve it.

**Comment by mbos** [comment]
Done and thanks

**Comment by mbos** [comment]
https://github.com/mbos/Pass4Win/releases/tag/version-1.1.8
