### ISSUE TITLE
Asked to upgrade but the original program stays running

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#94]
I started 1.1.7. It says there is an update. I say yes so it opens a browser and the new version downloads. Now I am prompted to run the freshly downloaded installer but the original app is still running so the install fails.

At the least when the browser is started Pass4Win could tell me to exit the application before continuing.

**Comment by mbos** [comment]
Never tried that, will look into that

**Comment by mbos** [comment]
Fixed in commit 2976cb52
