### ISSUE TITLE
Git pull reports as success even when it fails

### ISSUE THREAD

**Issue by TheCraiggers** [mbos/Pass4Win#95]
I've seen this happen both when using HTTPS internal git management with an obviously bad password, and also with external repo management. I mash the repo sync button, and it reports "Successfully pulled from Git server" with the current time, even though nothing seems to be pulled.

EDIT: Restarted the application, and was prompted for my GPGkey passphrase, which was a first (this is a new install). After that, my passwords showed up finally and I can no longer replicate this bug. Of course, now I have other problems, but I'll make a new issue for that as it's different.

**Comment by mbos** [comment]
Okay so initial pull issue. I'll look into it.

**Comment by mbos** [comment]
Same issue as #96
