### ISSUE TITLE
Quitting the application and opening again, this doesn't request a password

### ISSUE THREAD

**Issue by danoffn** [mbos/Pass4Win#98]
After entering the password, I pressed the Quit button (I supposed that the app will close completely), then I opened again the app and I could see my passwords without entered any password.
Pass4Win 1.2.0 running on Windows 7

**Comment by mbos** [comment]
The GPG keymanager keeps your password stored in memory for a couple of minutes. The default is I believe 5 minutes. Assuming you have kleopatra as keymanager you can adjust that setting in the keymanager.

This is works as designed and lies outside the scope of pass4win.

**Comment by danoffn** [comment]
Ok, thank you. I will check kleopatra.
