### ISSUE TITLE
Closed pass4win and uninstalled. Still running.

### ISSUE THREAD

**Issue by shaleh** [mbos/Pass4Win#99]
The zombie lives in task manager. I had to kill it before I could install the new version.

**Comment by mbos** [comment]
If this is an issue with 1.2.0: Did you manually uninstall as stated in the release notes?

If you did the manual uninstall do you have some additional info, maybe from the windows logging?

**Comment by shaleh** [comment]
This was while uninstalling 1.1.9.54 to install 1.2.0.

I closed the program. Uninstalled it. Installed the new version and received the warning it was still running. There was no visible icon but I could see it in task manager.

**Comment by mbos** [comment]
Okay, I need a starting point to find out what went wrong, are there pass4win related entries in your application log or error log of windows?

**Comment by shaleh** [comment]
Nothing related to pass4win anything in my logs.

My best guess is this scenario.

1.1.9.54 is installed and running.
I close the window but not the tray icon
I uninstalled 1.1.9.54.
Somehow pass4win is still running but without a visible sign
Begin to install 1.2.0 and notice the problem

**Comment by mbos** [comment]
OK, I'm gonna treat this as a one off event. If I see it again I'll reference this issue.
